version: "3.7"

services:
  app:
    build: .
    container_name: alshinky_app
    ports:
      - 8000:8000
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:8.0
    container_name: alshinky_db
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASS: "${DB_PASSWORD}"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-volume:

networks:
  app-network:
    driver: bridge
